# Generated by Django 5.2.8 on 2025-11-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Roast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_text", models.TextField(help_text="The original resume text")),
                ("roast_text", models.TextField(help_text="The AI-generated roast")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "upvotes",
                    models.IntegerField(default=0, help_text="Number of upvotes"),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
